const Recommended = [
  {
    head: "PG near DIT UNIVERSITY",
    imgPath: "./images/house-imgs/house.jpg",
    desc: "from ₹8,000/month",
    isVerified: 0,
    isLiked: 0,
  },
  {
    head: "Affordable PG in Sector 62 Noida",
    imgPath: "./images/house-imgs/house7.jpg",
    desc: "from ₹6,500/month",
    isVerified: 1,
    isLiked: 1,
  },
  {
    head: "Cozy Room near MG Road",
    imgPath: "./images/house-imgs/house18.jpg",
    desc: "from ₹9,000/month",
    isVerified: 1,
    isLiked: 0,
  },
  {
    head: "Studio Room in Pune",
    imgPath: "./images/house-imgs/house22.jpg",
    desc: "from ₹12,000/month",
    isVerified: 0,
    isLiked: 1,
  },
  {
    head: "Shared PG near DLF Cyber Hub",
    imgPath: "./images/house-imgs/house15.jpg",
    desc: "from ₹7,000/month",
    isVerified: 1,
    isLiked: 1,
  },
  {
    head: "Spacious Room in Saket",
    imgPath: "./images/house-imgs/house4.jpg",
    desc: "from ₹10,000/month",
    isVerified: 1,
    isLiked: 0,
  },
  {
    head: "Modern PG in Bangalore",
    imgPath: "./images/house-imgs/house12.jpg",
    desc: "from ₹11,000/month",
    isVerified: 0,
    isLiked: 1,
  },
  {
    head: "Furnished Room in Dehradun",
    imgPath: "./images/house-imgs/house29.jpg",
    desc: "from ₹6,000/month",
    isVerified: 1,
    isLiked: 0,
  },
  {
    head: "Budget PG in Rohini",
    imgPath: "./images/house-imgs/house9.jpg",
    desc: "from ₹5,500/month",
    isVerified: 0,
    isLiked: 0,
  },
  {
    head: "Room near Rajiv Chowk Metro",
    imgPath: "./images/house-imgs/house21.jpg",
    desc: "from ₹9,500/month",
    isVerified: 1,
    isLiked: 1,
  },
];

const InCity = [
  {
    head: "Luxury PG in Connaught Place",
    imgPath: "./images/house-imgs/house11.jpg",
    desc: "from ₹14,000/month",
    isVerified: 1,
    isLiked: 1,
  },
  {
    head: "PG for Girls in Karol Bagh",
    imgPath: "./images/house-imgs/house17.jpg",
    desc: "from ₹8,500/month",
    isVerified: 1,
    isLiked: 0,
  },
  {
    head: "Room near Delhi University",
    imgPath: "./images/house-imgs/house2.jpg",
    desc: "from ₹7,000/month",
    isVerified: 0,
    isLiked: 1,
  },
  {
    head: "AC Room in Laxmi Nagar",
    imgPath: "./images/house-imgs/house14.jpg",
    desc: "from ₹9,500/month",
    isVerified: 1,
    isLiked: 1,
  },
  {
    head: "PG near Hauz Khas",
    imgPath: "./images/house-imgs/house28.jpg",
    desc: "from ₹8,000/month",
    isVerified: 0,
    isLiked: 0,
  },
  {
    head: "Shared Room in South Delhi",
    imgPath: "./images/house-imgs/house23.jpg",
    desc: "from ₹7,200/month",
    isVerified: 1,
    isLiked: 1,
  },
  {
    head: "Single Room in Janakpuri",
    imgPath: "./images/house-imgs/house5.jpg",
    desc: "from ₹10,500/month",
    isVerified: 1,
    isLiked: 0,
  },
  {
    head: "Room in Uttam Nagar",
    imgPath: "./images/house-imgs/house8.jpg",
    desc: "from ₹6,800/month",
    isVerified: 0,
    isLiked: 0,
  },
  {
    head: "Girls PG in Pitampura",
    imgPath: "./images/house-imgs/house27.jpg",
    desc: "from ₹9,800/month",
    isVerified: 1,
    isLiked: 1,
  },
  {
    head: "PG in Rajouri Garden",
    imgPath: "./images/house-imgs/house30.jpg",
    desc: "from ₹7,900/month",
    isVerified: 0,
    isLiked: 0,
  },
];

const NearArea = [
  {
    head: "PG near Graphic Era",
    imgPath: "./images/house-imgs/house10.jpg",
    desc: "from ₹6,500/month",
    isVerified: 1,
    isLiked: 1,
  },
  {
    head: "Room near ISBT Dehradun",
    imgPath: "./images/house-imgs/house13.jpg",
    desc: "from ₹8,000/month",
    isVerified: 0,
    isLiked: 0,
  },
  {
    head: "Room near Prem Nagar",
    imgPath: "./images/house-imgs/house24.jpg",
    desc: "from ₹5,500/month",
    isVerified: 1,
    isLiked: 0,
  },
  {
    head: "PG near Rajpur Road",
    imgPath: "./images/house-imgs/house6.jpg",
    desc: "from ₹7,800/month",
    isVerified: 0,
    isLiked: 1,
  },
  {
    head: "Room near Ballupur",
    imgPath: "./images/house-imgs/house16.jpg",
    desc: "from ₹6,000/month",
    isVerified: 1,
    isLiked: 1,
  },
  {
    head: "Single Room near Clock Tower",
    imgPath: "./images/house-imgs/house20.jpg",
    desc: "from ₹7,500/month",
    isVerified: 0,
    isLiked: 0,
  },
  {
    head: "PG near EC Road",
    imgPath: "./images/house-imgs/house19.jpg",
    desc: "from ₹8,200/month",
    isVerified: 1,
    isLiked: 1,
  },
  {
    head: "Room in Vasant Vihar",
    imgPath: "./images/house-imgs/house25.jpg",
    desc: "from ₹9,000/month",
    isVerified: 0,
    isLiked: 1,
  },
  {
    head: "PG in Jakhan",
    imgPath: "./images/house-imgs/house26.jpg",
    desc: "from ₹6,900/month",
    isVerified: 1,
    isLiked: 0,
  },
  {
    head: "Affordable Room near Kaulagarh",
    imgPath: "./images/house-imgs/house3.jpg",
    desc: "from ₹5,800/month",
    isVerified: 0,
    isLiked: 0,
  },
];

export { NearArea, Recommended, InCity };
