const PGReviews = [
  // DEHDITbc51ed
  {
    RID: "DEHDITbc51ed",
    review:
      "Loved my stay here during college. Super close to DIT and the environment is peaceful — perfect for studying.",
    finalRating: 4.3,
    communityAndEnvironmentRating: 4.5,
    valueForMoneyRating: 4.2,
    locationRating: 4.7,
    foodRating: 3.9,
    landlordRating: 4.3,
    username: "ritik_dit22",
    date: "2025-05-11",
  },
  {
    RID: "DEHDITbc51ed",
    review:
      "Rooms are spacious and cleaned regularly. The staff is friendly, especially the warden uncle!",
    finalRating: 4.3,
    communityAndEnvironmentRating: 4.5,
    valueForMoneyRating: 4.2,
    locationRating: 4.7,
    foodRating: 3.9,
    landlordRating: 4.3,
    username: "muskan_singh",
    date: "2025-04-25",
  },
  {
    RID: "DEHDITbc51ed",
    review:
      "Food is homely but gets a little repetitive. Still better than most PGs I've seen in Dehradun.",
    finalRating: 4.3,
    communityAndEnvironmentRating: 4.5,
    valueForMoneyRating: 4.2,
    locationRating: 4.7,
    foodRating: 3.9,
    landlordRating: 4.3,
    username: "adityasharma01",
    date: "2025-05-03",
  },
  {
    RID: "DEHDITbc51ed",
    review:
      "Wi-Fi is decent. Faced a few power cuts during monsoon but they have a backup generator now.",
    finalRating: 4.3,
    communityAndEnvironmentRating: 4.5,
    valueForMoneyRating: 4.2,
    locationRating: 4.7,
    foodRating: 3.9,
    landlordRating: 4.3,
    username: "kritika_13",
    date: "2025-04-30",
  },
  {
    RID: "DEHDITbc51ed",
    review:
      "Perfect for DIT students. Walkable distance and very safe locality. Would recommend 100%.",
    finalRating: 4.3,
    communityAndEnvironmentRating: 4.5,
    valueForMoneyRating: 4.2,
    locationRating: 4.7,
    foodRating: 3.9,
    landlordRating: 4.3,
    username: "yash_t",
    date: "2025-05-15",
  },
  {
    RID: "DEHDITbc51ed",
    review:
      "Shared room felt a bit cramped at first but it’s well-managed and affordable for students.",
    finalRating: 4.3,
    communityAndEnvironmentRating: 4.5,
    valueForMoneyRating: 4.2,
    locationRating: 4.7,
    foodRating: 3.9,
    landlordRating: 4.3,
    username: "neha.m",
    date: "2025-04-17",
  },
  {
    RID: "DEHDITbc51ed",
    review:
      "Laundry service is available and works fine. Wish they had a small gym though!",
    finalRating: 4.3,
    communityAndEnvironmentRating: 4.5,
    valueForMoneyRating: 4.2,
    locationRating: 4.7,
    foodRating: 3.9,
    landlordRating: 4.3,
    username: "shivam_07",
    date: "2025-05-05",
  },
  {
    RID: "DEHDITbc51ed",
    review:
      "Stayed here for 1.5 years. It really felt like a second home. Clean and calm atmosphere.",
    finalRating: 4.3,
    communityAndEnvironmentRating: 4.5,
    valueForMoneyRating: 4.2,
    locationRating: 4.7,
    foodRating: 3.9,
    landlordRating: 4.3,
    username: "priya_dit",
    date: "2025-05-01",
  },

  // NOISEC7eb4aa
  {
    RID: "NOISEC7eb4aa",
    review:
      "Modern PG with great facilities. AC, RO water, even a mini fridge in the room!",
    finalRating: 4.6,
    communityAndEnvironmentRating: 4.8,
    valueForMoneyRating: 4.4,
    locationRating: 4.9,
    foodRating: 4.2,
    landlordRating: 4.7,
    username: "rohan_techie",
    date: "2025-05-10",
  },
  {
    RID: "NOISEC7eb4aa",
    review:
      "Bit expensive but you get what you pay for. Close to metro station and IT parks.",
    finalRating: 4.6,
    communityAndEnvironmentRating: 4.8,
    valueForMoneyRating: 4.4,
    locationRating: 4.9,
    foodRating: 4.2,
    landlordRating: 4.7,
    username: "ayushi_noida",
    date: "2025-05-06",
  },
  {
    RID: "NOISEC7eb4aa",
    review:
      "Security is tight here. Biometric entry and CCTV everywhere. I felt very safe.",
    finalRating: 4.6,
    communityAndEnvironmentRating: 4.8,
    valueForMoneyRating: 4.4,
    locationRating: 4.9,
    foodRating: 4.2,
    landlordRating: 4.7,
    username: "ankur_123",
    date: "2025-05-02",
  },
  {
    RID: "NOISEC7eb4aa",
    review:
      "Food quality is great on most days. Sometimes breakfast is a bit cold, but overall fine.",
    finalRating: 4.6,
    communityAndEnvironmentRating: 4.8,
    valueForMoneyRating: 4.4,
    locationRating: 4.9,
    foodRating: 4.2,
    landlordRating: 4.7,
    username: "megha_vibes",
    date: "2025-04-28",
  },
  {
    RID: "NOISEC7eb4aa",
    review:
      "My room had a private balcony — loved having coffee there in the evenings.",
    finalRating: 4.6,
    communityAndEnvironmentRating: 4.8,
    valueForMoneyRating: 4.4,
    locationRating: 4.9,
    foodRating: 4.2,
    landlordRating: 4.7,
    username: "shrey27",
    date: "2025-05-12",
  },
  {
    RID: "NOISEC7eb4aa",
    review:
      "Only downside: the Wi-Fi occasionally lags during office hours. Could be improved.",
    finalRating: 4.6,
    communityAndEnvironmentRating: 4.8,
    valueForMoneyRating: 4.4,
    locationRating: 4.9,
    foodRating: 4.2,
    landlordRating: 4.7,
    username: "deepak_j",
    date: "2025-04-26",
  },
  {
    RID: "NOISEC7eb4aa",
    review:
      "They even have a game room and rooftop lounge. Honestly felt more like a hostel than a PG!",
    finalRating: 4.6,
    communityAndEnvironmentRating: 4.8,
    valueForMoneyRating: 4.4,
    locationRating: 4.9,
    foodRating: 4.2,
    landlordRating: 4.7,
    username: "riya_b",
    date: "2025-05-08",
  },
  {
    RID: "NOISEC7eb4aa",
    review:
      "Clean washrooms, 24/7 hot water, and cooperative staff. Smooth experience overall.",
    finalRating: 4.6,
    communityAndEnvironmentRating: 4.8,
    valueForMoneyRating: 4.4,
    locationRating: 4.9,
    foodRating: 4.2,
    landlordRating: 4.7,
    username: "anmol.dev",
    date: "2025-05-04",
  },

  // GURMG c68efd
  {
    RID: "GURMG c68efd",
    review:
      "Luxurious PG setup. Feels like a co-living space more than a traditional PG.",
    finalRating: 4.7,
    communityAndEnvironmentRating: 4.6,
    valueForMoneyRating: 4.5,
    locationRating: 4.8,
    foodRating: 4.3,
    landlordRating: 4.9,
    username: "harshit_mg",
    date: "2025-05-01",
  },
  {
    RID: "GURMG c68efd",
    review:
      "Great for working professionals. Walking distance to metro and malls like Sahara & MGF.",
    finalRating: 4.7,
    communityAndEnvironmentRating: 4.6,
    valueForMoneyRating: 4.5,
    locationRating: 4.8,
    foodRating: 4.3,
    landlordRating: 4.9,
    username: "isha_k",
    date: "2025-05-13",
  },
  {
    RID: "GURMG c68efd",
    review:
      "Bit noisy outside due to traffic, but inside the PG it’s calm and soundproof.",
    finalRating: 4.7,
    communityAndEnvironmentRating: 4.6,
    valueForMoneyRating: 4.5,
    locationRating: 4.8,
    foodRating: 4.3,
    landlordRating: 4.9,
    username: "varun.g",
    date: "2025-04-30",
  },
  {
    RID: "GURMG c68efd",
    review:
      "Manager is responsive to complaints and maintenance is quick. Thumbs up.",
    finalRating: 4.7,
    communityAndEnvironmentRating: 4.6,
    valueForMoneyRating: 4.5,
    locationRating: 4.8,
    foodRating: 4.3,
    landlordRating: 4.9,
    username: "nandini.dev",
    date: "2025-04-22",
  },
  {
    RID: "GURMG c68efd",
    review:
      "Room interiors are really nice — wooden floor, good lighting, and comfy beds.",
    finalRating: 4.7,
    communityAndEnvironmentRating: 4.6,
    valueForMoneyRating: 4.5,
    locationRating: 4.8,
    foodRating: 4.3,
    landlordRating: 4.9,
    username: "rahulmg",
    date: "2025-05-06",
  },
  {
    RID: "GURMG c68efd",
    review:
      "Shared room but partitioned smartly. Felt like I had my own private space.",
    finalRating: 4.7,
    communityAndEnvironmentRating: 4.6,
    valueForMoneyRating: 4.5,
    locationRating: 4.8,
    foodRating: 4.3,
    landlordRating: 4.9,
    username: "deepa_kr",
    date: "2025-05-09",
  },
  {
    RID: "GURMG c68efd",
    review:
      "Food is outsourced, so it’s restaurant-quality most of the time. No complaints.",
    finalRating: 4.7,
    communityAndEnvironmentRating: 4.6,
    valueForMoneyRating: 4.5,
    locationRating: 4.8,
    foodRating: 4.3,
    landlordRating: 4.9,
    username: "amit.1999",
    date: "2025-05-03",
  },
  {
    RID: "GURMG c68efd",
    review:
      "I’ve changed 3 PGs in Gurgaon — this one was the best balance of price and quality.",
    finalRating: 4.7,
    communityAndEnvironmentRating: 4.6,
    valueForMoneyRating: 4.5,
    locationRating: 4.8,
    foodRating: 4.3,
    landlordRating: 4.9,
    username: "rashika_s",
    date: "2025-05-14",
  },

  // PUNCENadd957
  {
    RID: "PUNCENadd957",
    review:
      "Super clean PG. They clean rooms and common areas daily without fail.",
    finalRating: 4.5,
    communityAndEnvironmentRating: 4.7,
    valueForMoneyRating: 4.6,
    locationRating: 4.6,
    foodRating: 4.1,
    landlordRating: 4.4,
    username: "jatin",
  },
  {
    RID: "PUNCENadd957",
    review:
      "The best part is the location — right in the heart of the city. Everything’s nearby.",
    finalRating: 4.5,
    communityAndEnvironmentRating: 4.7,
    valueForMoneyRating: 4.6,
    locationRating: 4.6,
    foodRating: 4.1,
    landlordRating: 4.4,
    username: "shraddha.23",
    date: "2025-04-25",
  },
  {
    RID: "PUNCENadd957",
    review: "Food is simple but hygienic. Loved the rajma-chawal days!",
    finalRating: 4.5,
    communityAndEnvironmentRating: 4.7,
    valueForMoneyRating: 4.6,
    locationRating: 4.6,
    foodRating: 4.1,
    landlordRating: 4.4,
    username: "sumit17",
    date: "2025-04-27",
  },
  {
    RID: "PUNCENadd957",
    review: "Warden aunty is sweet and always ready to help. Feels homely.",
    finalRating: 4.5,
    communityAndEnvironmentRating: 4.7,
    valueForMoneyRating: 4.6,
    locationRating: 4.6,
    foodRating: 4.1,
    landlordRating: 4.4,
    username: "ananya_v",
    date: "2025-05-02",
  },
  {
    RID: "PUNCENadd957",
    review:
      "Wi-Fi is strong, even during peak hours. No buffering during Netflix binges!",
    finalRating: 4.5,
    communityAndEnvironmentRating: 4.7,
    valueForMoneyRating: 4.6,
    locationRating: 4.6,
    foodRating: 4.1,
    landlordRating: 4.4,
    username: "ravi.ch",
    date: "2025-04-29",
  },
  {
    RID: "PUNCENadd957",
    review:
      "Perfect place for students from PU and nearby colleges. Very student-friendly.",
    finalRating: 4.5,
    communityAndEnvironmentRating: 4.7,
    valueForMoneyRating: 4.6,
    locationRating: 4.6,
    foodRating: 4.1,
    landlordRating: 4.4,
    username: "neeraj_pu",
    date: "2025-05-04",
  },
  {
    RID: "PUNCENadd957",
    review:
      "Rooms are decent in size. Mattress quality could be better, though.",
    finalRating: 4.5,
    communityAndEnvironmentRating: 4.7,
    valueForMoneyRating: 4.6,
    locationRating: 4.6,
    foodRating: 4.1,
    landlordRating: 4.4,
    username: "komal_01",
    date: "2025-04-26",
  },
  {
    RID: "PUNCENadd957",
    review:
      "Affordable, quiet, and well-maintained. I’ll recommend it to any newcomer in Chandigarh.",
    finalRating: 4.5,
    communityAndEnvironmentRating: 4.7,
    valueForMoneyRating: 4.6,
    locationRating: 4.6,
    foodRating: 4.1,
    landlordRating: 4.4,
    username: "siddharth.chd",
    date: "2025-05-07",
  },
];
